// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkOrderApp.Data;

#nullable disable

namespace WorkOrderApp.Migrations
{
    [DbContext(typeof(WorkOrderAppContext))]
    [Migration("20260402233433_InitialRebuild")]
    partial class InitialRebuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkOrderApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@applevalley.gov",
                            Name = "Admin",
                            Password = "Password!0",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "cheryl@applevalley.gov",
                            Name = "Cheryl Smith",
                            Password = "Password!0",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mike@applevalley.gov",
                            Name = "Mike Rogers",
                            Password = "Password!0",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("WorkOrderApp.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToId = 3,
                            CreatedAt = new DateTime(2026, 3, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light fixture in hallway is flickering.",
                            Location = "Main hallway near reception desk.",
                            Priority = 1,
                            Status = 1,
                            Title = "Fix broken light"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToId = 2,
                            CreatedAt = new DateTime(2026, 3, 27, 11, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Maintenance room door hinge is loose.",
                            Location = "Maintenance room on the second floor.",
                            Priority = 0,
                            Status = 1,
                            Title = "Replace door hinge"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 28, 8, 45, 0, 0, DateTimeKind.Utc),
                            Description = "The air vents in the conference room are dirty and need cleaning.",
                            Location = "Conference room on the first floor.",
                            Priority = 1,
                            Status = 0,
                            Title = "Clean Air Vents"
                        },
                        new
                        {
                            Id = 4,
                            AssignedToId = 2,
                            CreatedAt = new DateTime(2026, 3, 28, 13, 15, 0, 0, DateTimeKind.Utc),
                            Description = "The faucet in the break room is leaking and needs to be repaired.",
                            Location = "Break room on the first floor.",
                            Priority = 1,
                            Status = 2,
                            Title = "Repair Leaking Faucet"
                        },
                        new
                        {
                            Id = 5,
                            AssignedToId = 3,
                            CreatedAt = new DateTime(2026, 3, 29, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fire extinguishers throughout the building need to be inspected and serviced if necessary.",
                            Location = "Throughout the building.",
                            Priority = 2,
                            Status = 3,
                            Title = "Inspect Fire Extinguishers"
                        },
                        new
                        {
                            Id = 6,
                            AssignedToId = 2,
                            CreatedAt = new DateTime(2026, 3, 29, 14, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Several carpet tiles in the lobby are stained and need to be replaced.",
                            Location = "Lobby area near the entrance.",
                            Priority = 0,
                            Status = 3,
                            Title = "Replace Carpet Tiles"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 30, 9, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Emergency exit lights need to be tested to ensure they are functioning properly.",
                            Location = "Emergency exits throughout the building.",
                            Priority = 2,
                            Status = 0,
                            Title = "Test Emergency Exit Lights"
                        },
                        new
                        {
                            Id = 8,
                            AssignedToId = 3,
                            CreatedAt = new DateTime(2026, 3, 30, 15, 45, 0, 0, DateTimeKind.Utc),
                            Description = "The HVAC system needs regular maintenance and servicing to ensure optimal performance.",
                            Location = "Rooftop mechanical room.",
                            Priority = 2,
                            Status = 1,
                            Title = "Service HVAC System"
                        },
                        new
                        {
                            Id = 9,
                            AssignedToId = 2,
                            CreatedAt = new DateTime(2026, 3, 29, 14, 20, 0, 0, DateTimeKind.Utc),
                            Description = "The elevator is making unusual noises and needs to be inspected and repaired if necessary.",
                            Location = "Elevator shaft near the lobby.",
                            Priority = 2,
                            Status = 2,
                            Title = "Repair Elevator"
                        },
                        new
                        {
                            Id = 10,
                            AssignedToId = 2,
                            CreatedAt = new DateTime(2026, 3, 30, 15, 45, 0, 0, DateTimeKind.Utc),
                            Description = "A window in the conference room is cracked and needs to be replaced.",
                            Location = "Conference room on the first floor.",
                            Priority = 1,
                            Status = 4,
                            Title = "Replace Broken Window"
                        },
                        new
                        {
                            Id = 11,
                            AssignedToId = 3,
                            CreatedAt = new DateTime(2026, 3, 29, 14, 20, 0, 0, DateTimeKind.Utc),
                            Description = "The roof needs to be inspected for any potential leaks or damage, especially after recent storms.",
                            Location = "Rooftop area.",
                            Priority = 2,
                            Status = 4,
                            Title = "Inspect Roof for Leaks"
                        });
                });

            modelBuilder.Entity("WorkOrderApp.Models.WorkOrderLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderLogs");
                });

            modelBuilder.Entity("WorkOrderApp.Models.WorkOrder", b =>
                {
                    b.HasOne("WorkOrderApp.Models.Employee", "AssignedTo")
                        .WithMany("WorkOrders")
                        .HasForeignKey("AssignedToId");

                    b.Navigation("AssignedTo");
                });

            modelBuilder.Entity("WorkOrderApp.Models.WorkOrderLog", b =>
                {
                    b.HasOne("WorkOrderApp.Models.WorkOrder", null)
                        .WithMany("History")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkOrderApp.Models.Employee", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("WorkOrderApp.Models.WorkOrder", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
