// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkOrderApp.Data;

#nullable disable

namespace WorkOrderApp.Migrations
{
    [DbContext(typeof(WorkOrderAppContext))]
    [Migration("20260402191408_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkOrderApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@kingscounty.ca",
                            Name = "Admin",
                            Password = "Password!0",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "cheryl@kingscounty.ca",
                            Name = "Cheryl",
                            Password = "Password!0",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mike@kingscounty.ca",
                            Name = "Mike",
                            Password = "Password!0",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("WorkOrderApp.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToId = 3,
                            CreatedAt = new DateTime(2026, 4, 2, 19, 14, 7, 764, DateTimeKind.Utc).AddTicks(8347),
                            Description = "Light fixture in hallway is flickering.",
                            Status = "Open",
                            Title = "Fix broken light"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToId = 2,
                            CreatedAt = new DateTime(2026, 4, 2, 19, 14, 7, 764, DateTimeKind.Utc).AddTicks(9427),
                            Description = "Maintenance room door hinge is loose.",
                            Status = "Open",
                            Title = "Replace door hinge"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 2, 19, 14, 7, 764, DateTimeKind.Utc).AddTicks(9430),
                            Description = "The air vents in the conference room are dirty and need cleaning.",
                            Status = "Open",
                            Title = "Clean Air Vents"
                        });
                });

            modelBuilder.Entity("WorkOrderApp.Models.WorkOrder", b =>
                {
                    b.HasOne("WorkOrderApp.Models.Employee", "AssignedTo")
                        .WithMany("WorkOrders")
                        .HasForeignKey("AssignedToId");

                    b.Navigation("AssignedTo");
                });

            modelBuilder.Entity("WorkOrderApp.Models.Employee", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
